version: "3.8"
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    volumes:
      -  D:/visual studio/docker-testapp/docker-testapp:/data/db 
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass

  mongo-express:
    image: mongo-express:latest   # will use your local image if it exists
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
